### ISSUE TITLE
Keycard spawning behing 'that keycard' requiring door

### ISSUE THREAD

**Issue by ThatOneRacoon** [brgmnn/autogen-rundown#9]
Seed: 2023_11_10
Version: v0.11.0
Keycard spawned deeper into the complex but the Keycard requiring door did.. not. Yes, this door requires the keycard listed in the progression.
What am I gonna do? :D
![image](https://github.com/brgmnn/autogen-rundown/assets/150458709/9638903b-36db-4660-8e53-428eb17b1889)

**Comment by brgmnn** [comment]
Thanks for the bug! I'll investigate and if it's still an issue will put in a fix 👍

**Comment by brgmnn** [comment]
Still investigating this one, I've verified that the keycard placement seems to be correct so whatever the issue was for this it's either fixed or a more subtle bug. I'll keep this open for now until I can get either a better fix or confirm that it's already been resolved.

I think this should not be happening frequently on the latest version though (0.17.0).

**Comment by brgmnn** [comment]
This should be fixed now in the [v0.19.0 release](https://github.com/brgmnn/autogen-rundown/releases/tag/v0.19.0). Thanks for taking the time to file a bug for me! Let me know if you see any other issues.
